### ISSUE TITLE
Error running in Multi-Module

### ISSUE THREAD

**Issue by schouten** [warmuuh/libsass-maven-plugin#10]
If I use the plugin in a single module pom everything works fine.
If I use a multi module pom it fails to read the input files.
The same issue is, when i start the pom from a different folder using -f to define the pom.xml in a different path.

**Comment by schouten** [comment]
Sample output:
```
[DEBUG] Configuring mojo com.github.warmuuh:libsass-maven-plugin:0.1.2:compile from plugin realm ClassRealm[plugin>com.github.wa
rmuuh:libsass-maven-plugin:0.1.2, parent: sun.misc.Launcher$AppClassLoader@1174ec5]
[DEBUG] Configuring mojo 'com.github.warmuuh:libsass-maven-plugin:0.1.2:compile' with basic configurator -->
[DEBUG]   (f) embedSourceContentsInSourceMap = false
[DEBUG]   (f) embedSourceMapInCSS = false
[DEBUG]   (f) generateSourceComments = false
[DEBUG]   (f) generateSourceMap = false
[DEBUG]   (f) includePath = Z:\work\vx\project\submodule/src/main/sass/plugins/
[DEBUG]   (f) inputPath = Z:\work\vx\project\submodule/src/main/webapp/
[DEBUG]   (f) inputSyntax = scss
[DEBUG]   (f) omitSourceMapingURL = false
[DEBUG]   (f) outputPath = Z:\work\vx\project\submodule\target\submodule-2.7.8-SNAPSHOT
[DEBUG]   (f) outputStyle = nested
[DEBUG]   (f) precision = 5
[DEBUG]   (f) project = MavenProject: de.conet.ics.ucrs:submodule:2.7.8-SNAPSHOT @ Z:\work\vx\project\project-uipro
totype\pom.xml
[DEBUG]   (f) sourceMapOutputPath = Z:\work\vx\project\submodule\target
[DEBUG] -- end configuration --
[DEBUG] Input Path=Z:/work/vx/project/submodule/src/main/webapp/
[DEBUG] Output Path=Z:\work\vx\project\submodule\target\submodule-2.7.8-SNAPSHOT
[DEBUG] Glob = glob:Z:/work/vx/project/submodule/src/main/webapp/{**/,}*.scss
[DEBUG] Processing File Z:\work\vx\project\submodule\src\main\webapp\main.scss
[ERROR] Error: File to read not found or unreadable: src\main\webapp\main.scss
```

**Comment by schouten** [comment]
For me it looks like the file will be read using the current working directory instead to use the complete path to the file.

**Comment by btwolfe79** [comment]
I'm having the exact same issue right now.  Hopefully someone has a work-around?

**Comment by btwolfe79** [comment]
I suspect it's some kind of mismatch in CompilationMojo.java where the glob is matching the files properly to be processed, but the "project.getBasedir().toPath().relativize()" is not providing the full path to libsass for the file.  It only works when the pom being executed is at the exact same dir level as ${basedir}

			out = compiler.compileFile( //
					project.getBasedir().toPath().relativize(inputFilePath).toString(), //
					project.getBasedir().toPath().relativize(outputFilePath).toString(), //
					project.getBasedir().toPath().relativize(sourceMapOutputPath).toString() //
			);

**Comment by btwolfe79** [comment]
Has anyone else been running into this issue?  Seems like a non-starter for most maven projects that have more than a single root pom.

**Comment by warmuuh** [comment]
i am working on it... don't have much time though...
but if you want, you can test already the stuff on the branch feature/issue-10

**Comment by warmuuh** [comment]
should be fixed now... 0.1.3 is deployed at central

**Comment by btwolfe79** [comment]
Great, thank you very much for the quick fix.  The central repo still only shows 0.1.2, so I'll give it a test once they have 0.1.3 available.  Thanks again.

**Comment by schouten** [comment]
I have tested 0.1.3 - works. Thanks - great job!
