### ISSUE TITLE
Update to recent libsass

### ISSUE THREAD

**Issue by btwolfe79** [warmuuh/libsass-maven-plugin#12]
Wondering if we could get a libsass library upgrade in the near future.  I believe the plugin is still based on libsass 3.1 (3.2.4 released recently).  We are getting a lot of intermittent failures of "java.lang.Error: Invalid memory access" during compilation.  They occur randomly and may fail in one run and then succeed immediately afterwards.

I'm hoping an upgrade to libsass might help as several bug fixes since 3.1 have been related to memory management.  

Thanks, much appreciated!

**Comment by warmuuh** [comment]
i will have a look into it. i just hope, there weren't many breaking changes (i am not staying up-to-date with libsass-development)

**Comment by btwolfe79** [comment]
Great, thanks.  Something else that may temporarily help would be a plugin <configuration> variable for "failOnError" that we could set to false.  This would allow the mvn build to succeed even if the libsass plugin reports an error. This could help in situations where the errors occur only on our dev windows machines but always work in our CI linux environment - just something to get us past the build failures if the css files aren't required.

**Comment by warmuuh** [comment]
i am not sure, if this is a good idea to have erroneous builds complete successful. if it fails on jenkins, you wont know that... but probably, i can still add it...

**Comment by warmuuh** [comment]
updated api to libsass version 3.2.4 and added a failOnError flag...
but i did not add binaries for osX because i could not ;)---   maybe someone can compile this for mac...
