### ISSUE TITLE
How to automatically compling sass or compass

### ISSUE THREAD

**Issue by jetma** [warmuuh/libsass-maven-plugin#15]
How to automatically compling sass or compass in Eclipse using libsass-maven-plugin?

**Comment by warmuuh** [comment]
you either execute the maven phase as build-step or you map it to a lifecycle phase explicitly and somhow tell eclipse what to do. i think, you find the right information here: http://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html#execute-plugin-goal
