### ISSUE TITLE
libsass.dylib for mac os is missing in latest version of plugin

### ISSUE THREAD

**Issue by tommix1987** [warmuuh/libsass-maven-plugin#16]
I'm getting a build failure currently when trying to use the plugin on Mac OS machines. I can see from history that file was removed recently while moving to newer version of libsass. Could file be added again to the library, recompiling it on each mac is bit painful and breaks the idea of maven dependencies being automatically downloaded from repository and doing their job immediately. Was there any particular reason to delete the file?
[PS] I'm seeing in the other issue that someone had a problem with 32bit windows JVM. Suggestion from @warmuuh was to create a pull request, shall I compile mac version of it and create a PR as well?

**Comment by warmuuh** [comment]
yes.. my inability to compile this stuff on mac or crosscompile... if you have the binary, you could add it as pull request.. would be nice

**Comment by tommix1987** [comment]
Cool, I will create PR within next few days.
Cheers,
TS
8 lip 2015 07:03 "Peter" <notifications@github.com> napisał(a):

**Comment by tommix1987** [comment]
Created a pull request containing pre-compiled libsass for MacOSX: https://github.com/warmuuh/libsass-maven-plugin/pull/17

**Comment by warmuuh** [comment]
thanks a lot for the PR, i will publish as soon as i find time

**Comment by tommix1987** [comment]
No problem, happy to help. Looking forward to see new version ;)
26 lip 2015 22:15 "Peter" <notifications@github.com> napisał(a):

**Comment by warmuuh** [comment]
published as version 0.1.5-libsass_3.2.4
