### ISSUE TITLE
Noob question about compiling sass files live

### ISSUE THREAD

**Issue by mitcheal** [warmuuh/libsass-maven-plugin#19]
I'm looking to simply link sass files in a html doc and have a js library render them.  Am I understanding that libsass does this?   I really don't like having to compiling locally its a huge turn off and barrier to getting into Sass,  I just want to link sass files and have a script render them live on the site.

**Comment by amasson88** [comment]
You can use https://github.com/edvin/libsass-filter
It's based on libsass-maven-plugin.

**Comment by warmuuh** [comment]
as this plugin is intended to compile the sass stuff, i guess, this question is not relevant... though the solution of amasson88 should work just fine ;)
