### ISSUE TITLE
Release new version with libsass 3.3.3

### ISSUE THREAD

**Issue by btwolfe79** [warmuuh/libsass-maven-plugin#25]
Looking for a new release tag built with the latest release of libsass (3.3.3) which fixes a lot of issues. 

https://github.com/sass/libsass/releases/tag/3.3.3

 Thanks!

**Comment by warmuuh** [comment]
i updated bindings to an external library which currently uses libsass 3.3.2, will this also help? otherwise we need to wait a little bit until they update their library (https://github.com/bit3/jsass)

**Comment by Danny02** [comment]
I opended an issue at the jsass project. I will try to create an own pull request if there is no change in the next days. Have to figure out how to build the binaries with their build system.

**Comment by warmuuh** [comment]
updated to newest jsass & deployed to central
