### ISSUE TITLE
0.2.x version cuts the end of final css

### ISSUE THREAD

**Issue by sam0var** [warmuuh/libsass-maven-plugin#30]
Hi there,

I tried this tool with 0.2.1-libsass_3.3.3 and 0.2.0-libsass_3.3.2 versions. With next config part:

```
<configuration>
    <inputPath>${styles.source.dir}</inputPath>
    <outputStyle>compressed</outputStyle>
    <outputPath>${styles.source.dir}</outputPath>
    <sourceMapOutputPath>${styles.source.dir}</sourceMapOutputPath>
</configuration>
```

The final css file has been cut at the end. And there is no reference to the source (sourceMappingURL).

With different options around sourceMap and outputStyle I got a different place of cutting.

Just open the final CSS in the editor, and you will notice the difference with the latest rules in scss.

Now, I use 0.1.7-libsass_3.2.4, because it hasn't this problem.

**Comment by warmuuh** [comment]
cannot reproduce. can you give an example scss file that fails to be compiled?

**Comment by warmuuh** [comment]
closed because of no response
