### ISSUE TITLE
Two unit tests fail on OSX

### ISSUE THREAD

**Issue by larsgrefer** [warmuuh/libsass-maven-plugin#34]
1. `testDefaultPrecision` expects `.something{padding:0 0.8em .71429 0.8em}` but gets `.something{padding:0 0.8em 0.71429 0.8em}`
2. `testHighPrecision` expects 
`.something{padding:0 0.8em .7142857143 0.8em}` but gets `.something{padding:0 0.8em 0.7142857143 0.8em}`

System Information:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
```

**Comment by larsgrefer** [comment]
see also:
bit3/jsass#20
bit3/jsass#21

**Comment by warmuuh** [comment]
I'll wait for bit3 to fix that...

**Comment by warmuuh** [comment]
updated to bit3 jsass 5.1.1, so this should be fixed
