### ISSUE TITLE
Fail on Teamcity and Mac

### ISSUE THREAD

**Issue by shamrox** [warmuuh/libsass-maven-plugin#40]
When I run this on my local it builds just fine but if I try to run maven on Teamcity or if another developer runs on Mac gets error also...here is my config:

`
            <plugin>
                <groupId>com.github.warmuuh</groupId>
                <artifactId>libsass-maven-plugin</artifactId>
                <version>0.2.4-libsass_3.3.4</version>
              <executions>
                <execution>
                  <id>compile-sass</id>
                  <goals>
                    <goal>compile</goal>
                  </goals>
                  <configuration>
                    <inputPath>${project.basedir}/src/main/content/jcr_root/etc/designs/namespace/styles</inputPath>
                    <outputPath>${project.basedir}/src/main/content/jcr_root/etc/designs/namespace/css</outputPath>
                    <includePath>${project.basedir}/src/main/content/jcr_root/etc/designs/namespace/sass;${project.basedir}/src/main/content/jcr_root/etc/designs/namespace/sass/Folder</includePath>
                    <outputStyle>compressed</outputStyle>
                    <generateSourceMap>true</generateSourceMap>
                    <sourceMapOutputPath>${project.basedir}/src/main/content/jcr_root/etc/designs/namespace/css</sourceMapOutputPath>
                    <omitSourceMapingURL>true</omitSourceMapingURL>
                  </configuration>
                </execution>
              </executions>
            </plugin>
`

**Comment by 19870213** [comment]
I think you can fix it by using ${path.separator} instead of ; in your includePath

**Comment by shamrox** [comment]
nope didn't work:

libsass-maven-plugin:0.2.4-libsass_3.3.4:compile (compile-sass) @ namespace.ui.apps ---
[17:40:59][namespace:namespace.ui.apps] Process exited with code 255

**Comment by shamrox** [comment]
I even tried to change slashes and that didn't work. There was a quick fix with Mac to put better paths in the import files, but that didn't work on build server

**Comment by warmuuh** [comment]
might get fixed with https://github.com/warmuuh/libsass-maven-plugin/pull/60
will close this issue, please reopen, if it is still an issue
