### ISSUE TITLE
lifecycle-mapping-metadata.xml causes endless rebuild loop in Eclipse

### ISSUE THREAD

**Issue by omicron81** [warmuuh/libsass-maven-plugin#45]
In Eclipse, the libsass-maven-plugin's `compile` goal is executed on every project refresh, because 
`<runOnIncremental>true</runOnIncremental>` is set in lifecycle-mapping-metadata.xml (#20).

This leads to ...
1. an endless rebuild loop if _"Refresh using native hooks or polling"_ is enabled in the Eclipse workspace settings, and
2. prevents publishing the project to Tomcat, because of _"Resource is out of sync with the file system: '/myProject/WebContent/resources/css/test.css'."_

Plugin configuration:

      <plugin>
      	<groupId>com.github.warmuuh</groupId>
      	<artifactId>libsass-maven-plugin</artifactId>
      	<version>0.2.5-libsass_3.3.6</version>
       	<executions>
      		<execution>
      			<goals>
      				<goal>compile</goal>
      			</goals>
      		</execution>
      	</executions>
      	<configuration>
      		<inputPath>${basedir}/WebContent/resources/scss/</inputPath>
      		<outputPath>${basedir}/WebContent/resources/css/</outputPath>
      	</configuration>
      </plugin>

What happens:
1. Refresh the project by pressing **F5**
2. Incremental build event is triggered
3. libsass-maven-plugin compiles test.scss -> test.css
4. Eclipse detects the changed resource test.css and triggers the next incremental build (2.), and so on ...

### Solution
To fix this, libsass-maven-plugin should only compile SCSS files that really have changed during incremental builds. For this, `BuildContext` should be used as described in the section "[Making Maven plugins compatible](http://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html)" of the M2Eclipse documentation:
> Mojos that runOnIncremental=true (the default), will be executed for any resource file, including all sources and generated files under target/. For performance and stability reasons it is absolutely essential to short-cut any time consuming work and all filesystem changes if there are no changes to the input sources processed by the mojo. For java code generating mojos, failure to act on relevant input changes only will almost certainly result in endless build – mojo generates .java files, which triggers jdt to generate .class files, which triggers the mojo to generate .java files, and so on.

**Comment by omicron81** [comment]
I can confirm that #57 (Release 0.2.8-libsass_3.4.4) fixes this issue. Thanks a lot!

**Comment by lourish** [comment]
Yes, huge improvement to performance, thanks.
