### ISSUE TITLE
Decimal litterals are truncated

### ISSUE THREAD

**Issue by npiguet** [warmuuh/libsass-maven-plugin#5]
I've encountered a strange behavior while using this plugin. For some reason all decimal litterals in my .scss file are truncated.

Here is an example of .scss code that causes the problem for me:
```
.sqw-contextMenu {
	li {
		a {
			padding: 0 0.8em 0 0.8em;
		}
	}
}
```

The code that is generated is the following: 
```
sqw-contextMenu li a {
    padding: 0 0em 0 0em;
}
```

This happens with version 0.1.1 of libsass-maven-plugin on Ubuntu 14.04.

This issue was previously reported to [libsass issue 923](https://github.com/sass/libsass/issues/923), but was closed as "cannot reproduce"

**Comment by npiguet** [comment]
Here's a little more information: It seems that all decimal litterals are parsed truncated, even in fractions. For example: 

```
.something {
  margin: (4.5/9);
}
```

is compiled to 
```
.something {
  margin:0.44444 }
```

when the value of the margin should clealy be `0.5`, and not `0.4444` (Which by the way is equal to `4/9`, so the `4.5` value was truncated to `4`, and then the fraction was calculated based on the truncated number.)

**Comment by npiguet** [comment]
The issue is actually a bug in libsass that only appears in locales for which the decimal separator is not `.`

**Comment by warmuuh** [comment]
glad to hear that :)
