### ISSUE TITLE
WebJar support

### ISSUE THREAD

**Issue by flipp5b** [warmuuh/libsass-maven-plugin#53]
Is there any way to use WebJars with this plugin?
I mean, if I want to use some Sass library, e.g. Susy, in my app, I should `@import` it to my scss file. But if the lib is added to pom as a WebJar dependency, the question is how to specify path to the lib in `@import`.

**Comment by warmuuh** [comment]
I fear that's not possible because libsass bindings are basically file-based and don't know anything about classpaths.

**Comment by flipp5b** [comment]
Yeah, after some investigation, I came to the same conclusion. It's sad.

**Comment by flipp5b** [comment]
@warmuuh, it looks like it's possible to implement WebJar support (actually, any scss source support) using custom `io.bit3.jsass.importer.Importer` implementation (see [this issue](https://github.com/bit3/jsass/issues/43)). Also, it already was implemented in [sass4clj](https://github.com/Deraen/sass4clj), and I going to implement it in plain Java as soon as I can.
What do you think, is it possible to incorporate this feature into libsass-maven-plugin?

**Comment by warmuuh** [comment]
Sounds like it should be possible... Might want to create a PR? I won't
have much time in near future for this sadly.

Am 14.04.2017 08:13 schrieb "Daniil Filippov" <notifications@github.com>:

**Comment by flipp5b** [comment]
Yeah, I will try to find time for this.
