### ISSUE TITLE
Css in Comments is Validated

### ISSUE THREAD

**Issue by fsomme2s** [warmuuh/libsass-maven-plugin#62]
Example: Somewhere in your css you have a line like this:

`
...
/* background-image: url(TODO: insert background once PNG is ready) */
...
`

=> Output of plugin: "Error: Invalid CSS after '...url("
Although the code is within a css comment (/* ... */)

**Comment by warmuuh** [comment]
this is just the plugin wrapping libsass via jsass. so either report it at https://github.com/bit3/jsass or https://github.com/sass/libsass. thanks
