### ISSUE TITLE
libsass-maven-plugin should be available on maven central

### ISSUE THREAD

**Issue by npiguet** [warmuuh/libsass-maven-plugin#7]
This is completely free, but each project to be published there must follow the requirements of Sonatype's OSSRH (OSS Repository Hosting).

See:
http://central.sonatype.org/pages/ossrh-guide.html
http://central.sonatype.org/pages/requirements.html

**Comment by warmuuh** [comment]
its [available](http://search.maven.org/#artifactdetails%7Ccom.github.warmuuh%7Clibsass-maven-plugin%7C0.1.2%7Cmaven-plugin) now on central. i actually did not wanted to do that but as jitpack does not support submodules, i guess, this is the best way

**Comment by npiguet** [comment]
Its honestly better that way, especially for corporate environments. For example, the company where I work has a nexus proxy that will only download artifacts from maven central. All our maven installs are configured to go through there, and we therefore can't easily access other repositories. I had to clone build and deploy libsass-maven-plugin manually on that repository to make it available to everyone. 

Having it on maven central just makes things easier for all the users.

Thanks for doing it :-)
