### ISSUE TITLE
Allow data context usage

### ISSUE THREAD

**Issue by bfd** [warmuuh/libsass-maven-plugin#8]
It would be great if the API also provided access to data contexts, so that the sass input can be created in-memory without having to write it to a temp file.
Granted, this is not so relevant for the maven plugin, but much more so when the Java classes are used as a library. Since the required changes are very small, I still think this would be a viable improvement.

**Comment by warmuuh** [comment]
this plugin is just a very thin layer over sass_compile_file and it does not hold any context at all... if you use this as library, i guess, you would basically use only the generated files (SassLibrary)

if you want to compile in-memory-stuff, you may be better off with generating the sass jni-interface for your project and use sass_compile (see https://github.com/sass/libsass/blob/master/sass_interface.h)? (or if you dont want to go through the hassle of generating this stuff, just instantiate a SassLibrary instance yourself (see SassCompiler.java for that...)

maybe i misunderstood... you can create a pull request maybe, if its only a small change, and i can see what you mean

**Comment by bfd** [comment]
It turns out data contexts cannot be used with the old deprecated sass_interface.h, it requires the new sass_context.h API, so this won't be such a trivial change after all.

**Comment by warmuuh** [comment]
i think its out of scope then or at least will be done when needed...
