### ISSUE TITLE
sass compilation fails in macOS Mojave 10.14.6 and Java 11

### ISSUE THREAD

**Issue by jashaj** [warmuuh/libsass-maven-plugin#80]
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
Java version: 11.0.4, vendor: AdoptOpenJDK (build 11.0.4+11.2)
Plugin version: 0.2.10-libsass_3.5.3

The plugin throws an error when it runs with AdoptOpenJDK 11.0.4+11.2. It worked with AdoptOpenJDK 11.0.4+11 and earlier. 

```
[ERROR] Failed to execute goal com.github.warmuuh:libsass-maven-plugin:0.2.10-libsass_3.5.3:compile (default) on project PROJECT-NAME: Execution default of goal com.github.warmuuh:libsass-maven-plugin:0.2.10-libsass_3.5.3:compile failed: An API incompatibility was encountered while executing com.github.warmuuh:libsass-maven-plugin:0.2.10-libsass_3.5.3:compile: java.lang.UnsatisfiedLinkError: /private/var/folders/rv/ksx523cj59g7ry121yycwn3c0000gn/T/libjsass-9722002274882154669/libjsass.dylib: dlopen(/private/var/folders/rv/ksx523cj59g7ry121yycwn3c0000gn/T/libjsass-9722002274882154669/libjsass.dylib, 1): no suitable image found.  Did find:
[ERROR]     /private/var/folders/rv/ksx523cj59g7ry121yycwn3c0000gn/T/libjsass-9722002274882154669/libjsass.dylib: code signature in (/private/var/folders/rv/ksx523cj59g7ry121yycwn3c0000gn/T/libjsass-9722002274882154669/libjsass.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Comment by 123Haynes** [comment]
@jashaj can you try if my fork works for you? https://gitlab.com/haynes/libsass-maven-plugin  
I updated quite a few dependencies and it's currently being build against jdk 11 and 13.

**Comment by jashaj** [comment]
@123Haynes I'll give it a try this week (need to make some changes in my setup for this).

**Comment by jashaj** [comment]
@123Haynes unfortunately your fork did not fix this specific problem. Meanwhile the error has been gone by updating to the latest AdoptOpenJDK 11 version via homebrew which was not available when I created the issue.

I'm closing it as it seems to be outside the scope of this project.

For reference: this is the specific JDK version that does trigger the error:
`brew cask install https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/38041a95aa84d5eca5bdaf3309f1fd77ac7d1e06/Casks/adoptopenjdk11.rb`
