### ISSUE TITLE
Why don't you separate SassCompiler and libsass-maven-plugin project?

### ISSUE THREAD

**Issue by kwon37xi** [warmuuh/libsass-maven-plugin#9]
Your project is the savior for web front-end developers which work with java based server applications.

If you separate this project to two different projects  for example "libsass-java-compiler" and "libsass-maven-plugin"(which depends on libsass-java-compiler), "libsass-java-compiler" will be the base project for other many java build tools' sass plugins(like ant, gradle, sbt, buildr,... or even servlet filter for sass).

**Comment by warmuuh** [comment]
you mean something like this: https://github.com/cathive/sass-java/
this is way more complete. i just added what i need to get the filebased compilation going.

and then, there is a webapp-filter for sasscompilation
on the fly which actually uses my lib as dependency..: https://github.com/edvin/libsass-filter

so i guess, there are better alternatives for these usecases

**Comment by kwon37xi** [comment]
Thank you for the links.
